name: Release

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        abi: [ "armeabi-v7a", "arm64-v8a", "x86", "x86_64" ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup the environment
        run: |
          sudo pip3 install meson==0.58.2
          sudo apt-get install nasm ninja-build

      - name: Build
        run: |
          export ANDROID_SDK_HOME=$ANDROID_HOME
          export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
          ./ffmpeg-android-maker.sh -all-free -all-gpl -android=21 -abis=${{ matrix.abi }}
