name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        abi: [ "armeabi-v7a", "arm64-v8a", "x86", "x86_64" ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup the environment
        run: |
          sudo pip3 install meson==0.58.2
          sudo apt-get install nasm ninja-build

      - name: Build
        run: |
          export ANDROID_SDK_HOME=$ANDROID_HOME
          export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
          ./ffmpeg-android-maker.sh -all-free -all-gpl -android=21 -abis=${{ matrix.abi }}

      - name: Upload build artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ffmpeg/${{ matrix.abi }}/bin/ffmpeg
          asset_name: ffmpeg-${{ matrix.abi }}
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload build artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ffmpeg/${{ matrix.abi }}/bin/ffprobe
          asset_name: ffprobe-${{ matrix.abi }}
          tag: ${{ github.ref }}
          overwrite: true
